### ISSUE TITLE
Cannot specify Android API levels that `AndroidSdkVersions` does not include

### ISSUE THREAD

**Issue by robinnorth** [superunitybuild/buildtool#105]
`PlayerSettings.Android.targetSdkVersion` and `PlayerSettings.Android.minSdkVersion` will accept int values for higher Android API levels than are defined in `UnityEditor.AndroidSdkVersions`, allowing the use of new Android SDKs (e.g. Unity 2022.2 defines values for up to Android 30 in `AndroidSdkVersions`, but Android 34 is the latest available at the time of writing), but because `BuildAndroid` relies on `AndroidSdkVersions` to get and set API levels, building for these newer API levels is not possible via SuperUnityBuild.

**Comment by Grave18** [comment]
Hello, meet this problem too, mimnimum target api must be 22 and maximum 34 for Unity 2022.3. Please fix 😢

**Comment by enpiech** [comment]
Hello, I have this problem too

**Comment by tre-dev** [comment]
Can this please be fixed? And is there a reason why it's so difficult to find this AndroidSdkVersions? I appreciate the work you're doing, but this is a breaking bug and it's a bit frustrating going through all of the hoops of getting the build tool ready for it not to work because some variables are outdated and I'm not able to just manually modify the enum. @robinnorth

**Comment by AldeRoberge** [comment]
I have the exact same problem, if we want to be able to publish on the Google Play store, new apps must target SDK version 33, which isn't even an option in AndroidSdkVersions. Take it from Unity's words : "These values should not be used to determine the highest supported API level.".

![image](https://github.com/superunitybuild/buildtool/assets/4276275/10247ad7-65fa-400a-8a09-c571ba770091)
![image](https://github.com/superunitybuild/buildtool/assets/4276275/012bfb51-e059-4006-b70b-44225fca01e0)
