### ISSUE TITLE
The ability to change build name

### ISSUE THREAD

**Issue by MaroLFC** [superunitybuild/buildtool#108]
Is there anyway to change build name other than it being the product name?

**Comment by robinnorth** [comment]
Hi @MaroLFC, what do you mean by 'change build name'? If you mean giving the release type a different label in the SuperUnityBuild UI to the product name, you can use 'Type Name' to set this:

<img width="314" alt="image" src="https://github.com/superunitybuild/buildtool/assets/3787255/e546253d-90cb-4919-97e2-2ea9589bd806">

**Comment by robinnorth** [comment]
Ah, I see. Currently this isn't possible with the GUI, but you could use a ScriptRunner build action to rename the built APK or ABB after the build has run.

**Comment by RobProductions** [comment]
For anyone keeping up with this issue, though the original PR was closed due to being stale, it was actually split into several smaller PRs and notably #116 has a working solution which will fulfill this request. If you want it earlier, you can grab [my fork](https://github.com/RobProductions/StellarUnityBuild) which I'm now using as an extension for experimental features. 

It lets you customize the binary name or sync it to the Product Name, and I took it one step further to let you sync Product Name, Company Name, or Bundle Identifier with your Project Settings too. I might try to get those new enhancements submitted as PRs as well once everything seems stable :)

**Comment by robinnorth** [comment]
This has been implemented in #116, thanks to @RobProductions 🎉
