### ISSUE TITLE
Last PostBuild action doesn't run

### ISSUE THREAD

**Issue by SlimeQ** [superunitybuild/buildtool#84]
I have 2 PostBuild actions set up in my build config.

The first runs, the second does not.

If I duplicate the second action, it runs once per build (not twice)

It seems like it's consistently skipping the last build action. Can't tell why because I don't have the source code. Downloaded via the recommended repository via Unity Package Manager.

EDIT: actually It is not simply the last action that isn't running. I added an empty action and added it to the list, and now only actions 1 and 3 run. This is very strange

**Comment by robinnorth** [comment]
Hi @SlimeQ, thanks for the issue report! Does this happen with a fresh project and build config, or is it specific to your Unity project? If it's the latter, it could hint at some bad serialization in your build config which could be fixed by creating a new one and recreating your settings. You can use `Assets > Create > SuperUnityBuild Settings` to try this.

To check out the source code of an installed UPM package, you can expand the `Packages` folder (underneath `Assets`) in the Project browser and look for the directory corresponding to the package you're interested in (e.g. `SuperUnityBuild`). You can then double click on source files and inspect and debug them in your IDE as with any other script in your project.
